version: '3.9'

services:
    cfgsvr1:
        container_name: cfgsvr1
        image: mongo
        command: mongod --configsvr --replSet cfgrs --bind_ip 0.0.0.0 --port 27017 --dbpath /data/db
        networks:
            - mongodb-net
        expose:
            - "27017"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - cfgsvr1:/data/db
    cfgsvr2:
        container_name: cfgsvr2
        image: mongo
        command: mongod --configsvr --replSet cfgrs --bind_ip 0.0.0.0 --port 27017 --dbpath /data/db
        networks:
            - mongodb-net
        expose:
            - "27017"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - cfgsvr2:/data/db
    cfgsvr3:
        container_name: cfgsvr3
        image: mongo
        command: mongod --configsvr --replSet cfgrs --bind_ip 0.0.0.0 --port 27017 --dbpath /data/db
        networks:
            - mongodb-net
        expose:
            - "27017"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - cfgsvr3:/data/db

volumes:
    cfgsvr1: {}
    cfgsvr2: {}
    cfgsvr3: {}

networks:
    mongodb-net:
        external: true
