version: '3.9'

services:
    shard2svr1:
        container_name: shard2svr1
        image: mongo
        command: mongod --shardsvr --replSet shard2rs --bind_ip 0.0.0.0 --port 27017 --dbpath /data/db
        networks:
            - mongodb-net
        expose:
            - "27017"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - shard2svr1:/data/db
    shard2svr2:
        container_name: shard2svr2
        image: mongo
        command: mongod --shardsvr --replSet shard2rs --bind_ip 0.0.0.0 --port 27017 --dbpath /data/db
        networks:
            - mongodb-net
        expose:
            - "27017"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - shard2svr2:/data/db
    shard2svr3:
        container_name: shard2svr3
        image: mongo
        command: mongod --shardsvr --replSet shard2rs --bind_ip 0.0.0.0 --port 27017 --dbpath /data/db
        networks:
            - mongodb-net
        expose:
            - "27017"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - shard2svr3:/data/db

volumes:
    shard2svr1: {}
    shard2svr2: {}
    shard2svr3: {}

networks:
    mongodb-net:
        external: true
