name: Shellcheck
on:
  push:
    paths:
      - "**.sh"
  pull_request:
    paths:
      - "**.sh"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck
        run: shellcheck -s sh build.sh
